In [1]:
import numpy as np
# formatting the float to be three digit 
float_formatter = lambda x: "%.3f" % x
import pandas as pd
np.set_printoptions(formatter={'float_kind':float_formatter})
from sklearn.datasets import make_circles
from sklearn.cluster import SpectralClustering, KMeans
from sklearn.metrics import pairwise_distances
from matplotlib import pyplot as plt
import networkx as nx
import seaborn as sns
sns.set()

In [2]:
df = pd.read_csv("HeartFailure.csv")
df.head()

ID   age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0   1  75.0        0                       582         0                 20   
1   2  55.0        0                      7861         0                 38   
2   3  65.0        0                       146         0                 20   
3   4  50.0        1                       111         0                 20   
4   5  65.0        1                       160         1                 20   

   high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1  265000.00               1.9           130    1   
1                    0  263358.03               1.1           136    1   
2                    0  162000.00               1.3           129    1   
3                    0  210000.00               1.9           137    1   
4                    0  327000.00               2.7           116    0   

   smoking  time  DEATH_EVENT  
0        0     4            1  
1        0     6            1  
2        1     7            1  
3        0     7            1  
4        0     8            1

In [3]:
df_cluster = df.iloc[:,1:13]

In [4]:
G = pairwise_distances(df_cluster, metric="euclidean")
G



array([[0.000, 7461.948, 103000.923, ..., 477002.371, 125013.720,
        130000.882],
       [7461.948, 0.000, 101651.227, ..., 478677.200, 123478.579,
        131865.228],
       [103000.923, 101651.227, 0.000, ..., 580003.223, 22118.198,
        233000.173],
       ...,
       [477002.371, 478677.200, 580003.223, ..., 0.000, 602000.104,
        347005.007],
       [125013.720, 123478.579, 22118.198, ..., 602000.104, 0.000,
        255009.637],
       [130000.882, 131865.228, 233000.173, ..., 347005.007, 255009.637,
        0.000]])

In [5]:
def draw_graph(G):
    pos = nx.spring_layout(G)
    nx.draw_networkx_nodes(G, pos)
    nx.draw_networkx_labels(G, pos)
    nx.draw_networkx_edges(G, pos, width=1.0, alpha=0.5)


In [7]:
Graph=nx.from_numpy_matrix(G)
draw_graph(Graph)

In [11]:
W = nx.adjacency_matrix(Graph)
print(W.todense())

[[0.000 7461.948 103000.923 ... 477002.371 125013.720 130000.882]
 [7461.948 0.000 101651.227 ... 478677.200 123478.579 131865.228]
 [103000.923 101651.227 0.000 ... 580003.223 22118.198 233000.173]
 ...
 [477002.371 478677.200 580003.223 ... 0.000 602000.104 347005.007]
 [125013.720 123478.579 22118.198 ... 602000.104 0.000 255009.637]
 [130000.882 131865.228 233000.173 ... 347005.007 255009.637 0.000]]


C:\Users\sitas\AppData\Local\Temp\ipykernel_8936\2902025618.py:1: FutureWarning: adjacency_matrix will return a scipy.sparse array instead of a matrix in Networkx 3.0.
  W = nx.adjacency_matrix(Graph)


In [22]:
# degree matrix
D = Graph.degree()
D

DegreeView({0: 298, 1: 298, 2: 298, 3: 298, 4: 298, 5: 298, 6: 298, 7: 298, 8: 298, 9: 298, 10: 298, 11: 298, 12: 298, 13: 298, 14: 298, 15: 298, 16: 298, 17: 298, 18: 298, 19: 298, 20: 298, 21: 298, 22: 298, 23: 298, 24: 298, 25: 298, 26: 298, 27: 298, 28: 298, 29: 298, 30: 298, 31: 298, 32: 298, 33: 298, 34: 298, 35: 298, 36: 298, 37: 298, 38: 298, 39: 298, 40: 298, 41: 298, 42: 298, 43: 298, 44: 298, 45: 298, 46: 298, 47: 298, 48: 298, 49: 298, 50: 298, 51: 298, 52: 298, 53: 298, 54: 298, 55: 298, 56: 298, 57: 298, 58: 298, 59: 298, 60: 298, 61: 298, 62: 298, 63: 298, 64: 298, 65: 298, 66: 298, 67: 298, 68: 298, 69: 298, 70: 298, 71: 298, 72: 298, 73: 298, 74: 298, 75: 298, 76: 298, 77: 298, 78: 298, 79: 298, 80: 298, 81: 298, 82: 298, 83: 298, 84: 298, 85: 298, 86: 298, 87: 298, 88: 298, 89: 298, 90: 298, 91: 298, 92: 298, 93: 298, 94: 298, 95: 298, 96: 298, 97: 298, 98: 298, 99: 298, 100: 298, 101: 298, 102: 298, 103: 298, 104: 298, 105: 298, 106: 298, 107: 298, 108: 298, 109: 298

In [23]:
degrees = [val for (node, val) in Graph.degree()]
# degree matrix
D = np.zeros((len(degrees), len(degrees)))
np.fill_diagonal(D, degrees)
print('degree matrix:')
print(D)


degree matrix:
[[298.000 0.000 0.000 ... 0.000 0.000 0.000]
 [0.000 298.000 0.000 ... 0.000 0.000 0.000]
 [0.000 0.000 298.000 ... 0.000 0.000 0.000]
 ...
 [0.000 0.000 0.000 ... 298.000 0.000 0.000]
 [0.000 0.000 0.000 ... 0.000 298.000 0.000]
 [0.000 0.000 0.000 ... 0.000 0.000 298.000]]


In [24]:
# laplacian matrix
L = D - W
print('laplacian matrix:')
print(L)

laplacian matrix:
[[298.000 -7461.948 -103000.923 ... -477002.371 -125013.720 -130000.882]
 [-7461.948 298.000 -101651.227 ... -478677.200 -123478.579 -131865.228]
 [-103000.923 -101651.227 298.000 ... -580003.223 -22118.198 -233000.173]
 ...
 [-477002.371 -478677.200 -580003.223 ... 298.000 -602000.104 -347005.007]
 [-125013.720 -123478.579 -22118.198 ... -602000.104 298.000 -255009.637]
 [-130000.882 -131865.228 -233000.173 ... -347005.007 -255009.637 298.000]]


In [25]:
e, v = np.linalg.eig(L)
# eigenvalues
print('eigenvalues:')
print(e)
# eigenvectors
print('eigenvectors:')
print(v)

eigenvalues:
[-36777136.524 15279836.778 10174542.567 2773759.180 2082285.111
 1117725.210 920599.850 658607.123 481194.948 372339.413 282541.743
 240500.922 199333.046 176749.234 154885.135 125862.523 121070.573
 99529.354 83230.968 79431.836 72674.756 70902.429 65860.775 55377.336
 51902.764 51218.658 42225.046 41144.965 37239.590 34470.401 32445.604
 29910.331 29089.671 27005.951 24560.204 22694.415 22258.960 21771.096
 20843.425 21448.712 17906.181 16324.074 15761.852 15624.456 14692.945
 13158.873 12619.164 12712.242 12052.634 11941.496 11439.659 11153.883
 11126.168 10311.176 10115.891 9939.593 9206.912 8947.473 9060.398
 8566.005 8278.475 8179.584 7565.638 7823.049 7785.508 7711.499 6995.943
 7225.395 7020.154 6507.979 6424.800 6013.092 5728.298 5231.297 5106.807
 5012.289 4913.212 4812.542 4775.603 4538.031 4631.255 4600.772 4462.973
 4100.290 4019.137 3981.924 3987.231 3950.550 3845.232 3788.408 3648.274
 3716.729 3561.375 3557.432 3524.236 3518.882 3503.671 3323.161 3269.141


In [26]:
fig = plt.figure()
ax1 = plt.subplot(121)
plt.plot(e)
ax1.title.set_text('eigenvalues')
i = np.where(e < 10e-6)[0]
ax2 = plt.subplot(122)
plt.plot(v[:, i[0]])
fig.tight_layout()
plt.show()

In [29]:
U = np.array(v[:, i[0]])
km = KMeans(init='k-means++', n_clusters=3)
df['clusters'] = km.fit_predict(U)
df

ID   age  anaemia  creatinine_phosphokinase  diabetes  \
0      1  75.0        0                       582         0   
1      2  55.0        0                      7861         0   
2      3  65.0        0                       146         0   
3      4  50.0        1                       111         0   
4      5  65.0        1                       160         1   
..   ...   ...      ...                       ...       ...   
294  295  62.0        0                        61         1   
295  296  55.0        0                      1820         0   
296  297  45.0        0                      2060         1   
297  298  45.0        0                      2413         0   
298  299  50.0        0                       196         0   

     ejection_fraction  high_blood_pressure  platelets  serum_creatinine  \
0                   20                    1  265000.00               1.9   
1                   38                    0  263358.03               1.1   
2                   20                    0  162000.00               1.3   
3                   20                    0  210000.00               1.9   
4                   20                    0  327000.00               2.7   
..                 ...                  ...        ...               ...   
294                 38                    1  155000.00               1.1   
295                 38                    0  270000.00               1.2   
296                 60                    0  742000.00               0.8   
297                 38                    0  140000.00               1.4   
298                 45                    0  395000.00               1.6   

     serum_sodium  sex  smoking  time  DEATH_EVENT  clusters  
0             130    1        0     4            1         0  
1             136    1        0     6            1         0  
2             129    1        1     7            1         0  
3             137    1        0     7            1         0  
4             116    0        0     8            1         0  
..            ...  ...      ...   ...          ...       ...  
294           143    1        1   270            0         0  
295           139    0        0   271            0         0  
296           138    0        0   278            0         1  
297           140    1        1   280            0         2  
298           136    1        1   285            0         2  

[299 rows x 15 columns]